from collections import Counter


def filter_new_queries(queries, last_timestamp):
    # Keep only the queries generated after the last processed timestamp
    return [q for q in queries if q["time"] > last_timestamp]


def calculate_total(new_queries):
    # Count the total number of new queries
    return len(new_queries)


def calculate_blocked(new_queries):
    # Count queries blocked by Pi-hole
    return sum(
        1 for q in new_queries
        if q.get("status") in ("GRAVITY", "BLOCKED")
    )


def calculate_qps(total, interval_seconds=300):
    # Calculate the average number of queries per second
    if interval_seconds > 0:
        return total / interval_seconds

    return 0.0


def calculate_blocked_percentage(blocked, total):
    # Calculate the percentage of blocked queries
    if total > 0:
        return (blocked / total) * 100

    return 0.0


def calculate_active_clients(new_queries):
    # Count the number of unique clients that generated queries
    clients = set()

    for q in new_queries:
        client = q.get("client")

        if isinstance(client, dict):
            ip = client.get("ip")

            if ip:
                clients.add(ip)

    return len(clients)


def calculate_queries_per_client(new_queries):
    # Count how many queries were generated by each client
    clients = [
        q.get("client", {}).get("ip")
        for q in new_queries
        if q.get("client")
    ]

    return Counter(clients)


def calculate_client_metrics(new_queries):
    # Calculate query statistics for each client
    client_stats = {}

    for q in new_queries:
        client = q.get("client", {})
        ip = client.get("ip")
        status = q.get("status")

        if not ip:
            continue

        if ip not in client_stats:
            client_stats[ip] = {
                "queries": 0,
                "blocked": 0,
                "cached": 0,
                "forwarded": 0
            }

        client_stats[ip]["queries"] += 1

        if status in ("GRAVITY", "BLOCKED"):
            client_stats[ip]["blocked"] += 1

        if status in ("CACHE", "CACHED"):
            client_stats[ip]["cached"] += 1

        if status == "FORWARDED":
            client_stats[ip]["forwarded"] += 1

    # Calculate blocked and cached percentages for each client
    for ip, stats in client_stats.items():
        total = stats["queries"]

        stats["blocked_pct"] = (
            stats["blocked"] / total * 100
            if total > 0
            else 0.0
        )

        stats["cached_pct"] = (
            stats["cached"] / total * 100
            if total > 0
            else 0.0
        )

    return client_stats


def calculate_query_types(new_queries):
    # Count the different DNS query types
    types = [
        q.get("type")
        for q in new_queries
        if q.get("type")
    ]

    return Counter(types)


def calculate_top_domains(queries, limit=10):
    # Count the most frequently requested base domains
    domains = [get_base_domain(q["domain"]) for q in queries]

    counter = Counter(domains)

    return dict(counter.most_common(limit))


def calculate_ip_version(new_queries):
    # Count queries generated by IPv4 and IPv6 clients
    ipv4 = 0
    ipv6 = 0

    for q in new_queries:
        client = q.get("client", {})
        ip = client.get("ip")

        if not ip:
            continue

        if ":" in ip:
            ipv6 += 1
        else:
            ipv4 += 1

    return {
        "IPv4": ipv4,
        "IPv6": ipv6
    }


def calculate_forwarded(new_queries):
    # Count queries forwarded to upstream DNS servers
    return sum(
        1 for q in new_queries
        if q.get("status") == "FORWARDED"
    )


def calculate_cached(new_queries):
    # Count queries answered from the Pi-hole cache
    return sum(
        1 for q in new_queries
        if q.get("status") in ("CACHE", "CACHED")
    )


def calculate_cached_percentage(cached, total):
    # Calculate the percentage of cached queries
    if total > 0:
        return (cached / total) * 100

    return 0.0


def get_base_domain(domain):
    # Reduce a full domain name to its base domain
    parts = domain.split(".")

    if len(parts) >= 2:
        return ".".join(parts[-2:])

    return domain